input/ts: ili9881h: Fix missing type specifier
error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
  309 | extern mp_test_result;
      | ~~~~~~ ^
      | int
1 error generated.

Signed-off-by: shygosh <mossynine@gmail.com>